FROM debian:bullseye-slim

RUN apt-get --yes update
RUN apt-get --yes upgrade
RUN apt-get --yes install cucumber
RUN apt-get --yes install ruby-httparty
RUN apt-get --yes install ruby-rspec

CMD ["cucumber", "features"]

COPY features /features
