FROM docker.io/python:3.12

WORKDIR /var/www

COPY requirements-integration.txt .
RUN pip install -r requirements-integration.txt

COPY features features/
RUN find

COPY docker/behave.ini ./

USER www-data

ENTRYPOINT ["behave"]
